version: "3.7"

services:
  app:
    image: golang:alpine
    command: sh -c "go run ."
    depends_on:
      - db
      - redis
    ports:
      - 4000:4000
    volumes:
      - ./:/go/src/gotodo
    working_dir: /go/src/gotodo

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 11111
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

volumes:
  postgresdb:
